### ISSUE TITLE
SyntaxError: The requested module 'permissionless' does not provide an export named 'walletClientToCustomSigner'

### ISSUE THREAD

**Issue by francelwebdev** [zerodevapp/kernel#76] opened 2024-01-30 21:27 UTC
node_modules/@zerodev/sdk/utils.ts:1
import { walletClientToCustomSigner } from "permissionless"

SyntaxError: The requested module 'permissionless' does not provide an export named 'walletClientToCustomSigner'

**Comment by leekt** [comment] 2024-01-31 12:33
seems to be duplicate of https://github.com/zerodevapp/sdk/issues/88, closing since it's relevant to sdk

**Closed by leekt** 2024-01-31 12:33 UTC
